### ISSUE TITLE
Need to be able to refetch and refresh in Agent-Configuration pages

### ISSUE THREAD

**Issue by snetsystems** [snetsystems/cloudhub#161]
Add refresh button & function in each Minions, Collector Control, Collector Config pages.

**Comment by Choidaeboem** [comment]
I have solved the problem... I leave the commit information.
------------------------------------------------------------------
Commit: 16ca68216ea927d640b170dff7fb3a1e3547dc12
Parents: ce5a06a21c1053738345dbe7024fe8699b41799d
Author: Choe DaeBeom <daebeom.choe@snetsystems.co.kr>
Committer: Choe DaeBeom <daebeom.choe@snetsystems.co.kr>
Date: Mon May 18 2020 09:09:31 GMT+0900 (한국 표준시) 

dbchoe: AgentPage: Added refresh feature and button at the top area
