### ISSUE TITLE
Telegraf config test feature

### ISSUE THREAD

**Issue by snetsystems** [snetsystems/cloudhub#218]
It can make sure if the config is working or not.
(input plugin only)

**Comment by jaemyeongroh** [comment]
add docker plugin 
[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
container_names = [ ]
timeout = "10s"
perdevice = true
total = false

error : permission denied
[inputs.docker] Error in plugin: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.21/info": dial unix /var/run/docker.sock: connect: permission denied

resolution
$ usermod -aG docker telegraf

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker

**Comment by snetsystems** [comment]
Move #253, close this.
