### ISSUE TITLE
Dashboard의 가로 길이가 길어질 때 가로 스크롤이 보이지 않는 현상

### ISSUE THREAD

**Issue by jaegeunha** [snetsystems/cloudhub#407]
# 수정 이유
* Dashboard의 가로 길이가 길어짐에도 불구하고 가로 스크롤이 보이지 않음

# 수정 전 UI
![Image](https://github.com/snetsystems/cloudhub/assets/100550323/6094c266-d67b-4363-a55a-ba2a0a1e2d7b)

**Comment by kim-jinhyeong** [comment]
수정 :  영역 하단에 가로 스크롤 추가


![Image](https://github.com/snetsystems/cloudhub/assets/68767855/b154a04e-ab8c-44e6-9fb5-e2c50419012e)
