### ISSUE TITLE
AgentConfiguration, Agent Console 접속 시 웹 소켓 URL에 붙는 Port 직접 지정

### ISSUE THREAD

**Issue by jaegeunha** [snetsystems/cloudhub#420]
# 수정 이유
* AgentConfiguration 탭에서, 웹 소켓으로 console 접속 시 포트가 자동으로 지정(80, 443)

# 수정 내용
*  Console 접속 시 Cloudhub URL의 포트를 직접 지정하여 웹 소켓 요청

# 테스트 항목
- [x] Console 접속 시 Cloudhub URL의 포트를 직접 지정하여 웹 소켓 요청
  - [x] 연결 여부 확인

**Comment by kim-jinhyeong** [comment]
```diff
const socketURL =
      protocol +
      window.location.hostname +
+   ':' +
+   window.location.port +
      '/cloudhub/v1/WebTerminalHandler?' +
      encodeURIComponent(urlParam)
```

host port 추가 예정
