### ISSUE TITLE
[CloudHub AI] Device Management API개발

### ISSUE THREAD

**Issue by kim-jinhyeong** [snetsystems/cloudhub#473]
# 개발 예정 API
## 장비 등록 관련 CRUD
1. 조회:
      * 개별
      * 일괄
2. 등록:
      * 개별
      * 일괄
3. 삭제:
      * 개별
      * 일괄
4. 수정:
     * 개별

## SNMP 관련
1. SNMP 연결 상태 확인 및 장비 정보 수집

**Comment by jaegeunha** [comment]
SNMP v3 테스트 및 ML/DL 설정 적용 시 Learning Ticscript 생성/업데이트와 관련된 작업 등은 각각 별도로 이슈를 생성하여 관리합니다.
