### ISSUE TITLE
AI Device 일괄 업로드에서 SuperAdmin Default만 모든 Org 허용

### ISSUE THREAD

**Issue by kim-jinhyeong** [snetsystems/cloudhub#480]

**Comment by kim-jinhyeong** [comment]
Device 일괄 업로드 시점에서 Org가 Default인 경우만 등록하려는 모든 Org에 대해서 허용 유무 확인필요

**Comment by snetsystems** [comment]
That a super admin can register devices associated with all organizations is consistent.
Therefore, I think enough as is.

I'll close this issue.
