### ISSUE TITLE
Infrastructure 페이지 속도 개선

### ISSUE THREAD

**Issue by jaegeunha** [snetsystems/cloudhub#528]
# 이슈 내용
* Infrastructure 페이지에서 Server Node의 개수가 많아질 경우, 로딩 시간과 페이지 반응 속도가 느려짐

# 개선 방안
## 1. Outline **labelsVisible** 옵션을 false로 설정

```diff
const outln = new mxOutline(this.graph, this.outline)
-// outln.outline.labelsVisible = true
```

* labelsVisible 옵션은 미니맵에 표시되는 **노드나 엣지의 레이블이 미니맵 화면에도 표시될지 여부**를 결정
* `outln.outline.labelsVisible = true` 부분을 주석 처리하면 미니맵의 이동 속도가 개선되는 것을 확인하였음.

## 3. 신호등 및 IPMI 전원 전체 랜더링 차단
* Modal 화면을 통해 Cell 전체의 신호등 및 IPMI 전원 랜더링 여부를 결정하는 화면을 추가

## 5. Topology 확장자 (.xml) 변경 고려
 * 지원되는 확장자가 XML 이외 없음 확인

**Comment by kim-jinhyeong** [comment]
## 동일 IP의 장비에서 IPMI를 통해 데이터 수집 시 아래 오류 발생
IPMI에서 "Insufficient resources to create new session" 오류 발생


![Image](https://github.com/user-attachments/assets/1a0433a5-c991-4440-9517-81c1580a4d8f)


## 이슈 설명:
IPMI를 사용하여 서버를 관리하는 도중, 새로운 세션을 생성하려고 할 때 "Insufficient resources to create new session" 오류 메시지가 발생합니다. 이 오류는 새로운 세션을 생성할 수 없음을 의미하며, 이는 주로 IPMI에서 허용된 세션 수를 초과하거나 시스템 리소스가 부족한 경우 발생합니다.

**Comment by kim-jinhyeong** [comment]
## Refresh 최적화
`fetchIntervalData()` 함수 내에서 `getIpmiStatus()`와 `getDetectedHostStatus()` 호출 시 각각 `graph.refresh()`를 수행하고 있었습니다. 이를 개선하기 위해 두 작업이 완료된 후 한 번만 `graph.refresh()`를 호출하는 방식으로 수정하였습니다.

## 수정 전 코드
```typescript
fetchIntervalData() {
  ...
  getIpmiStatus();
  getDetectedHostStatus();
}
```
- `getIpmiStatus()`와 `getDetectedHostStatus()` 각각에서 `this.graph.refresh()`를 호출함으로써 그래프가 두 번 갱신되는 문제가 있었습니다.

## 수정 후 코드
```typescript
fetchIntervalData() {
  ...
  try {
    getIpmiStatus();
    getDetectedHostStatus();
  } finally {
    this.graph.refresh();
  }
}
```
- 두 작업이 모두 완료된 후에 `this.graph.refresh()`를 한 번만 호출하도록 변경하였습니다.

## 성능 비교

아래는 개별 Refresh와 통합 Refresh의 성능 비교 결과입니다:

| 횟수 | 통합 Refresh (초) | 개별 Refresh (초) | 성능 차이 (%) |
|:---:|:-----------------:|:-----------------:|:-------------:|
|  1  |        3.01       |        4.67       |     35.55     |
|  2  |        3.03       |        4.63       |     34.56     |
|  3  |        2.52       |        4.62       |     45.45     |
|  4  |        3.17       |        4.90       |     35.31     |
|  5  |        3.68       |        4.52       |     18.58     |
| **평균** |     **3.08**    |     **4.67**    |   **33.98**   |

## 결론

통합 Refresh 방식으로 변경한 결과, 평균적으로 약 `34%`의 성능 개선이 이루어졌습니다.
