### ISSUE TITLE
Too slow Salt-minion's list up on the outage cases

### ISSUE THREAD

**Issue by snetsystems** [snetsystems/cloudhub#67]
In "Agent configuration" menu, if at lease one or more of Salt-Minion's responses are pending by something like HW or NW outage, anyway whatever causes, whole listing is too slow.

I need to discuss how to resolve as a good way.

**Comment by yongsikgi** [comment]
1. Make sure the minions are connected using manage.allowed in salt.runners.manage
  - salt-run manage.allowed (no commands will be sent to minions)
  ex) minion1
      minion2 
      minion3 (server shotdown or salt-minion service stop)

    $ salt-run manage.allowed
      minion1
      minion2

2. Do not send next step salt-api commands to disconnected minions

**Comment by snetsystems** [comment]
That's good idea.
You can go ahead as this method.
Best regards,

**Comment by snetsystems** [comment]
There is occurred an abnormal case in the edge router that Salt runner cannot be gotten the managed IP.
Therefore, Salt is normal but the minion in the edge router disappears in "CH Agent Confuguration" page.

So, to resolve, reopen this issue.

**Comment by snetsystems** [comment]
I figured out the proper(better) way.
Like the following, the way is what induces users can recognize their status.

1. Popup button("**Check Minions**") click in Agent Configuration/Minions menu → Popup modal window then request using **manage.status** module.
<pre>
<code>
# Request body
{
    "token": "6f7eb80e64af06f8997b65ece9ed438b9dc2df5533744e623cdb540bd7a8e1e5",
    "eauth": "pam",
    "client": "runner",
    "fun": "manage.status"
}

# Response (will take for a long time)
{
    "return": [
        {
            "up": [
                "jack-server-01.snet.com"
            ],
            "down": [
                "jack-server-02.snet.com"
            ]
        }
    ]
}
</code>
</pre>
2. Show that minions against "**down**"
3. With this mention,

> "**For the more quick response, you'd better reject or delete against down minions.**"

4. With "**Reject**", "**Delete**", "**Cancel**" buttons.

Is there anything else?

**Comment by snetsystems** [comment]
Now, I seem to be resolved this issue by the following way.
1. CH calls on the first loading only in "Agent Configuration > Minions" menu, then stores into the redux store for reusing within other tabs.
2. You can reject or delete an unusable minion server for shorter latency.

So, close this issue.
